version: "2.0"

services:
  serge:
    image: cryptoandcoffee/akash-serge:0.1.3
    expose:
      - port: 8008
        as: 80
        to:
          - global: true
deployment:
  serge:
    lagrange:
      profile: serge
      count: 1