version: "2.0"

services:
  umaprotocol:
    image: yuravorobei/uma-protocol
    expose:
      - port: 3000
        as: 80
        to:
          - global: true

deployment:
  umaprotocol:
    lagrange:
      profile: umaprotocol
      count: 1
